# MoveIt controllers configuration
moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

arm_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  joints:
    - shoulder_pan
    - shoulder_lift
    - elbow_flex
    - wrist_flex
    - wrist_roll
  action_ns: follow_joint_trajectory
  default: true

gripper_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  joints:
    - gripper
  action_ns: follow_joint_trajectory
  default: true
